### ISSUE TITLE
Off by one

### ISSUE THREAD

**Issue by Gerv-G** [MrBotDeveloper/This-Repo-Has-110-Stars#2]
As the title says...

I happen to come across this repo and saw the star count mismatch
![image](https://user-images.githubusercontent.com/25771885/224889161-4f1b169c-4d32-406c-adeb-b82380f19086.png)

Nope, I didn't star this repo and removed it.

**Comment by MrBotDeveloper** [comment]
Thanks for reporting the bug 👾, it has been fixed now.
